### ISSUE TITLE
ADTlang does not work

### ISSUE THREAD

**Issue by ArieVanLeeuwen** [nschiele/ADT-Web-App#8]
Every form of appending a node to the root node using ADTlang does not work. I am using a HP-laptop and I have tried chrome and edge. I have tried every form of appening I could think of. Here are some examples:

create attack node "Rob bank"; 
append “Gain Acess” to “Rob bank”;

create attack node "Rob Bank";
create attack node "Gain Access";
append "Gain Access" to "Rob Bank";

create attack node "Rob Bank";
create attack node "Gain Access" append to "Rob Bank";

"Gain Access" append to "Rob Bank";

create attack node "Rob Bank"; create attack node "Gain Access" append to "Rob Bank";

allong with several variants of these examples

I do not know how to work arround this issue, the other form of appending using the child tab does work. Using any form of ADTlang however, does not

**Comment by cesarg1337** [comment]
Hi Arie,

What seems to be the issue for the first case is not ADTLang, but the way you use quotation marks;
you use “ instead of ". ADTLang scans for strings, and strings should be put inside the latter.

For all other cases, I tried reproducing your errors in several browsers on several devices; it all performed as expected and did not result in any error.
I can therefore conclude that this is an error for you personally and not an ADT-Web-App issue.

Do e-mail us if you have this problem on other devices too, then I will reopen this issue and look at it more deeply.


Regards,
Cesar
